name: etkinlik_takip
description: "A new Flutter project."
publish_to: 'none' # 

version: 0.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #Navigation
  auto_route: ^9.2.2



  #Utility
  equatable: ^2.0.7
  get_it: ^8.0.3
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  flutter_localizations:
    sdk: flutter

  #State
  flutter_bloc: ^9.1.0

  #Firebase
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  firebase_messaging: ^15.2.10
  cloud_firestore: ^5.6.12

  #database
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #UI
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  firebase_auth: ^5.7.0
  loader_overlay: ^5.0.0
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  flutter_spinkit: ^5.2.1
  country_code_picker: ^3.3.0
  mask_text_input_formatter: ^2.9.0
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.3.1






dev_dependencies:

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  integration_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:

  assets:
    - assets/images/nations/
    - assets/svg/

  uses-material-design: true
flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/images/logo.png
  ios: true
  remove_alpha_ios: true



