// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMyKh0UZEq8DSI0Fy_Kme3bL54DISerI0',
    appId: '1:787399845323:web:007cea2118efb57a52c24e',
    messagingSenderId: '787399845323',
    projectId: 'etkinlik-takip-99e51',
    authDomain: 'etkinlik-takip-99e51.firebaseapp.com',
    storageBucket: 'etkinlik-takip-99e51.firebasestorage.app',
    measurementId: 'G-M399Y13T2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhdy-9yUEQoRdzua7klkN9CJkqOd1kD1A',
    appId: '1:787399845323:android:c430a87c0d50e8a552c24e',
    messagingSenderId: '787399845323',
    projectId: 'etkinlik-takip-99e51',
    storageBucket: 'etkinlik-takip-99e51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2pW2Fu0sCH-9ipffhV7OdWJSKBxl7c4',
    appId: '1:787399845323:ios:5ee76c96e2ea171152c24e',
    messagingSenderId: '787399845323',
    projectId: 'etkinlik-takip-99e51',
    storageBucket: 'etkinlik-takip-99e51.firebasestorage.app',
    iosBundleId: 'com.gokalpyildiz.etkinlikTakip',
  );
}
